### ISSUE TITLE
Gradle 3.4-rc-1: "Resolving configuration 'apiElements' directly is not allowed"

### ISSUE THREAD

**Issue by juergenzimmermann** [jeremylong/dependency-check-gradle#31] opened 2017-02-02 08:12 UTC
After upgrading to Gradle 3.4-rc-1 I'm getting the following stacktrace when I invoke `gradle dependencyCheck`:

```
09:04:45.327 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
09:04:45.327 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
09:04:45.327 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
09:04:45.327 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':dependencyCheck'.
09:04:45.328 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Resolving configuration 'apiElements' directly is not allowed
09:04:45.328 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
09:04:45.328 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
09:04:45.330 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dependencyCheck'.
09:04:45.330 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
09:04:45.330 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
09:04:45.330 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
09:04:45.331 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
09:04:45.331 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
09:04:45.331 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
09:04:45.331 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
09:04:45.331 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
09:04:45.331 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
09:04:45.331 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
09:04:45.331 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
09:04:45.331 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
09:04:45.331 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
09:04:45.332 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
09:04:45.332 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
09:04:45.332 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
09:04:45.332 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
09:04:45.332 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
09:04:45.332 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
09:04:45.332 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
09:04:45.332 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
09:04:45.332 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.IllegalStateException: Resolving configuration 'apiElements' directly is not allowed
09:04:45.332 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.assertResolvingAllowed(DefaultConfiguration.java:818)
09:04:45.332 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:419)
09:04:45.333 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getResolvedConfiguration(DefaultConfiguration.java:414)
09:04:45.333 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getResolvedConfiguration(Unknown Source)
09:04:45.333 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.artifacts.Configuration$getResolvedConfiguration$3.call(Unknown Source)
09:04:45.333 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.owasp.dependencycheck.gradle.tasks.Check$_scanDependencies_closure2.doCall(Check.groovy:205)
09:04:45.333 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.owasp.dependencycheck.gradle.tasks.Check.scanDependencies(Check.groovy:202)
09:04:45.333 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.owasp.dependencycheck.gradle.tasks.Check$scanDependencies.callCurrent(Unknown Source)
09:04:45.333 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.owasp.dependencycheck.gradle.tasks.Check.check(Check.groovy:81)
09:04:45.333 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
09:04:45.333 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
09:04:45.333 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
09:04:45.333 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
09:04:45.333 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
09:04:45.334 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
09:04:45.334 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
09:04:45.334 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
09:04:45.334 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 20 more
```

**Comment by jeremylong** [comment] 2017-02-05 14:16
I've run checked a few projects with Gradle 3.4-rc-1 and I have not seen this issue come up. Any chance you can provide an example build.gradle that causes this issue?  I'm also wondering if this is a dependencyCheck issue or something that needs to be reported to the [gradle team](https://gradle.org/release-candidate/)?

**Comment by stefanneuhaus** [comment] 2017-02-05 14:38
You have to apply the "java" plugin in order to reproduce the issue:
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath('org.owasp:dependency-check-gradle:1.4.5')
    }
}

apply plugin: 'org.owasp.dependencycheck'
apply plugin: 'java'
```

With 3.4 they introduced a couple of configurations that cannot be resolved directly. A simple fix would be to hard-code a blacklist of these configurations, but this seems very fragile. I am currently looking for a more robust and elegant solution.

**Comment by stefanneuhaus** [comment] 2017-02-05 14:47
As a workaround you can configurate dependency-check to skip these configurations. Add the following to your `build.gradle`:
```
dependencyCheck {
    skipConfigurations=["apiElements", "implementation", "runtimeElements", "runtimeOnly", "testImplementation", "testRuntimeOnly"]
}
```

**Comment by stefanneuhaus** [comment] 2017-02-05 15:07
I have provided a PR for a fix: #32

Since Gradle 3.3 the Configuration class was extended by the information whether it can be resolved: [Configuration.isCanBeResolved()](https://docs.gradle.org/release-candidate/javadoc/org/gradle/api/artifacts/Configuration.html#isCanBeResolved())

Since Gradle 3.4 e.g. some configurations of the Java Plugin make use of it.

**Comment by stefanneuhaus** [comment] 2017-02-06 08:31
After analyzing thew issue I suppose that the Gradle change was done on purpose. I brought up the question in the [Gradle Forum](https://discuss.gradle.org/t/3-4-rc-1-3-3-resolving-configurations-may-be-disallowed-and-throw-illegalstateexception/21470) whether the change should be mentioned as Breaking Change in the Release Notes.

**Closed** 2017-02-07 11:05 UTC

**Comment by jeremylong** [comment] 2017-02-07 11:06
@stefanneuhaus thanks for the research (and PR) on this one! I truly appreciate it.

**Comment by johnscancella** [comment] 2017-03-01 00:18
I just upgraded to 3.4 and using version 1.4.5 of this plugin I am still seeing the issue. What version is this fix in?

**Comment by jeremylong** [comment] 2017-03-01 13:42
The fix has been implemented but we have not yet published a new release.
I'll try to do this on saturday.

Jeremy

**Comment by johnscancella** [comment] 2017-03-01 13:44
@jeremylong thanks so much! I love your plugin, keep up the great work!

**Comment by dodgex** [comment] 2017-03-17 09:18
Hey there, I'd like to know if there is a new ETA for the 1.4.6 release containing this fix.

Thanks in advance! :)

**Comment by jeremylong** [comment] 2017-03-18 11:44
I just pushed 1.4.5.1 - I was trying to hold off for 1.5.0 but there are changes in the core engine that are taking longer then I hoped.
